### ISSUE TITLE
Run Spectools in the Terminal?

### ISSUE THREAD

**Issue by curtisklarsen** [caljorden/spectools#1]
I want to be able to run this on a remote machine via SSH in a terminal.  I once saw someone do this with ncurses or something.  Is this possible?

**Comment by caljorden** [comment]
You must be thinking of the spectools_curses application.  It is a part of this repo.  Building it happens automatically if you have the curses development headers installed.

**Comment by curtisklarsen** [comment]
Ok, I found it and got it working.  Can we display the 5GHz channels
somehow at the bottom of the spectrum view?  Right now it is blank.

On 2019-08-03 10:44, caljorden wrote:

> You must be thinking of the spectools_curses application. It is a part of this repo. Building it happens automatically if you have the curses development headers installed. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/caljorden/spectools/issues/1?email_source=notifications&amp;email_token=AGUN2AP55SUF4SQCW7TV7QDQCWYX3A5CNFSM4IIMCPPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3PRZVY#issuecomment-517938391
[2]
